def mycoinflip():
  return True
if mycoinflip():
    print("Head")
else:
    print("Tail") 
    

x = 13
y = 92
z = 69
    
A = "addition"
B = "subtraction"  
C = "multiplication"  
D = "division"

print(A,x+y+z) 
print(B,x-y-z)
print(C,x*y*z)
print(D,x/y/z)

E = "KISHORI"
F = "SHYAMA"
G = E+F
H = E+"AND"+F

print(G)
print(H)


def mygirlsisloyal():
  return True
if mygirlsisloyal ():
    print("she is not cheat")
    
else:
   print("she is  cheat")    

  